name: "GitHub Snake"
on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # âœ… This is required to get a local git repo
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Commit generated files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/*
          git commit -m "Update GitHub snake SVGs" || echo "No changes to commit"
          git push
